### ISSUE TITLE
JS_Window_Find() vs JS_Window_GetTitle()

### ISSUE THREAD

**Issue by Buy-One** [juliansader/js_ReaScriptAPI#3]
Hi Julian

Just want to ascertain that JS_Window_GetTitle() functions as designed because the description reads

> Returns the title (if any) of the specified window.

Yet after getting floating docker window handle with JS_Window_Find() and using it to retrieve its name what's returned is REAPER_dock instead of the actual window name.

E.g.  `reaper.JS_Window_GetTitle(reaper.JS_Window_Find('Toolbar Docker', false))`

Same with "Docker" window.

Breader's BR_Win32_GetWindowText() gives the same result.

----------------------------------------------------------------------------------------------

Also JS_Window_GetParent() to which child handle is passed returns handle different than the one returned with JS_Window_Find() used to get the said child handle with JS_Window_FindChild()

E.g.  `reaper.JS_Window_Find('Toolbar Docker', false)) ~= reaper.JS_Window_GetParent(reaper.JS_Window_FindChild(reaper.JS_Window_Find('Toolbar Docker', false)))`

**Comment by juliansader** [comment]
Could you please report this issue in the Cockos forums, https://forum.cockos.com/showthread.php?t=212174, so that we can discuss it in more detail?

I suspect that there may be another window with "Toolbar docker" in the title, so JS_Window_Find is returning that window rather than the one you intended.  Perhaps try FindTop with exact="true"?  Or try ArrayFind or ListFind and see how many windows are returned.  If more than one is returned, you may need to check them one-by-one.  

(FindChild requires three arguments, so something is amiss in the second code sample.)

**Comment by Buy-One** [comment]
> (FindChild requires three arguments, so something is amiss in the second code sample.)

Indeed, my mistake, in my tests i of course used all three. Thank you for suggestions.

UPD: setting the argument to TRUE eliminates the discrepancies
